### PR TITLE
Streams - work in progress

### PR DESCRIPTION
**Pull request by SiAdcock**
Hi @Jameskmonger 

This PR allows the user to specify their reporter in the package.json of their project:

```json
"modunit": {
  "reporter": "tap-diff"
}
```

I've also introduced `through` which provides a nicer way of creating a readable/writable stream, and allows us to pipe through to the reporter programmatically, rather than on the command line. So now you can run the tests using:

```
$ node path/to/test.js
```

There are a few problems so far:

1) Tests are failing, specifically those with multiple variables. Let's temporarily ignore those for now
2) The code at the top of session.js is horrible!
3) For the purpose of testing modunit itself, we default to reporting using `tap-diff`. Maybe we can handle this in a better way.

Pushing all the above aside, do you have any other thoughts? Is there anything that doesn't fit right? Would you do something differently? Or is there something about this approach that codes us into a corner, or breaks something irreparably?

I'm happy to keep working on this if you think there's merit in it, although I'd probably need your help to get the tests passing!

### CODE REVIEW

**Comment by Jameskmonger** [comment]
This looks great @SiAdcock! I'm happy to merge.

One question: why did you use `queue` when sending data?

**Comment by SiAdcock** [comment]
`queue` is slightly more flexible, it handles flow logic if you need to pause or resume the stream's state. Not necessary for us at the moment though, we can revert to `write` if you prefer.

**Comment by Jameskmonger** [comment]
Nope I don't have an issue with `queue`, was just wondering what the difference was :smile: Merging now.

**Comment by SiAdcock** [comment]
:tada:

**Pull request merged**
