### PR TITLE
Symlink on install

### PR DESCRIPTION
**Pull request by SiAdcock**
Hi @Jameskmonger 

When I run `npm test`, I would normally expect the tests to be run. As it currently stands, `npm test` does two things: first symlinking `node_modules/modunit` to the `lib` directory; the running of the tests is then delegated to the `test:run` script.

It feels strange for a developer to have to run `npm test` to execute tests the first time after installing, and then use `npm run test:run` to execute subsequent test runs.

This change would perform the symlink on `npm install`, allowing us to run tests directly whenever `npm test` is run.

### CODE REVIEW

**Comment by Jameskmonger** [comment]
I use `npm test` to run the tests - the symlinking is quite fast and just ensures that there are no issues with the link. I've worked with projects before where for some reason the link is deleted or there is a problem with it, and it can be quite hard to diagnose.

I don't think linking every time there is a test is too much of an issue given the pain points I've encountered with it before, although I'd be open to merging this PR if you're confident that it's not too much of an issue to have it on install (given that users can then just run `npm install` again to fix the link)

**Comment by SiAdcock** [comment]
Cool. In my opinion (emphasis on opinion), `npm test` should only run the tests, not do things that should be handled as part of the installation of the module. If installation went wrong, or the link was deleted for some other reason, having the `npm test` script mask the issue is not going to help in the long run.

I would normally say with confidence "it's not an issue to have the symlink happen on install!" However, since you've actually encountered issues before, my confidence is probably not worth much in this instance! :smile: 

Incidentally, can you remember how the issues arose?

**Comment by Jameskmonger** [comment]
I can't remember how they arose, but I'm happy to merge this in and simply inform anyone experiencing a problem to run `npm install` again :smile:

**Comment by SiAdcock** [comment]
Very well, on my head be it :speak_no_evil: 

They could also run `npm run link`

**Pull request merged**
